name: my testing job

on:
    push:
        branches:
            - master

jobs:
    print_greeting:   
      runs-on: ubuntu-latest

      steps:
        - name: "check out tyhe code"
          uses: actions/checkout@v2
        - name: print greeting
          run: echo "Hello, welcom to my printing page"
        - name: "login to the docker hub account"
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERBNAME }}  
            PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
        - name: build our code imae
          env:
              IMAGE_NAME: testing
              VERSION: 1
              USERNAME: mutiuadeniyi290
          run: |
              docker build -t $USERNAME/$IMAGE_NAME:$VERSION .
              Ddocker push $USERNAME/$IMAGE_NAME:$VERSION


          

