name: ci

on:
  push:
    branches:
      - master

jobs:
    
  print-greeting:
    runs-on: ubuntu-latest

    steps:
    - name: check out the code
      uses: actions/checkout@v2

    - name: print greeting
      run: "Welcome to my world"


    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Build and tag the Docker image
    #   run: |
    #     docker build -t ${{ secrets.DOCKER_USERNAME }}/my-simple-html-app:latest .

    # - name: Push the Docker image
    #   run: |
    #     docker push ${{ secrets.DOCKER_USERNAME }}/my-simple-html-app:latest